import {
  Coffee,
  Croissant,
  CupSoda,
  Facebook,
  Home,
  IceCream,
  Instagram,
  LayoutGrid,
  Moon,
  SunMedium,
  Pizza,
  Beer,
  Salad,
  UtensilsCrossed,
  Sandwich,
  Wand2,
} from "lucide-react";

export const Icons = {
  sun: SunMedium,
  moon: Moon,
  instagram: Instagram,
  wan: Wand2,
  home: Home,
  beer: Beer,
  salad: Salad,
  cupSoda: CupSoda,
  layoutGrid: LayoutGrid,
  croissant: Croissant,
  coffee: Coffee,
  pizza: Pizza,
  sandwich: Sandwich,
  utensilsCrossed: UtensilsCrossed,
  iceCream: IceCream,
  facebook: Facebook,
};
